# 01 — Data Understanding
فحص ملفات CSV، الأبعاد، الأنواع، القيم المفقودة، التكرارات، والمفاتيح المحتملة قبل أي تنظيف.

In [1]:
from pathlib import Path
import pandas as pd

RAW = Path('../data/raw')
expected = ['customers.csv', 'accounts.csv', 'transactions.csv', 'branches.csv', 'products.csv']
available = [p.name for p in RAW.glob('*.csv')]
missing = sorted(set(expected) - set(available))
print(f'CSV files found: {len(available)}')
print('Missing expected files:', missing or 'None')

CSV files found: 9
Missing expected files: None

In [2]:
tables = {}
for path in sorted(RAW.glob('*.csv')):
    try:
        tables[path.stem] = pd.read_csv(path)
    except Exception as exc:
        print(f'Could not read {path.name}: {exc}')

overview = []
for name, frame in tables.items():
    overview.append({
        'table': name,
        'rows': len(frame),
        'columns': len(frame.columns),
        'duplicate_rows': int(frame.duplicated().sum()),
        'missing_cells': int(frame.isna().sum().sum()),
    })
pd.DataFrame(overview)

           table    rows  columns  duplicate_rows  missing_cells
0       accounts     600       14               0            322
1       branches      12        4               0              0
2          cards     358       13               0              0
3      customers     200       21               0              0
4          loans      95       13               0              0
5      merchants     254        9               0              0
6       products      24        4               0              0
7  subscriptions    1333       12               0           1134
8   transactions  476202       30               0         687045

In [3]:
for name, frame in tables.items():
    print(f'\n--- {name} ---')
    display(pd.DataFrame({'dtype': frame.dtypes.astype(str), 'missing': frame.isna().sum(), 'unique': frame.nunique(dropna=True)}))
    display(frame.head(3))

--- accounts ---

                   dtype  missing  unique
account_id        object        0     600
customer_id       object        0     200
iban              object        0     600
bic               object      322       8
bank_name         object        0      12
account_type      object        0      24
role              object        0       7
opened_at         object        0     530
initial_balance  float64        0     600
current_balance  float64        0     600
overdraft_limit  float64        0      25
status            object        0       1
branch_id          int64        0      12
product_id         int64        0      24

,account_id,customer_id,iban,bic,bank_name,account_type,role,opened_at,initial_balance,current_balance,overdraft_limit,status,branch_id,product_id
0,A00000001,C0000001,FR763000271023RU98WRUTXJ652,CRSYFRPPXXX,Crédit Synthétique,compte_courant,CURRENT,2005-11-01,7495.69,-3248.088344,2500.0,active,5,7
1,A00000002,C0000001,FR7630002624617YT1GY9I2Y486,CRSYFRPPXXX,Crédit Synthétique,livret_a,SAVINGS,2006-11-24,5497.94,38019.530000,0.0,active,5,18
2,A00000003,C0000001,FR763000222777R8EKCSH7UL282,CRSYFRPPXXX,Crédit Synthétique,assurance_vie,RETIREMENT,2011-07-01,291436.09,291436.090000,0.0,active,5,1

--- branches ---

              dtype  missing  unique
branch_id     int64        0      12
branch_name  object        0      12
city         object        0       1
source_note  object        0       1

,branch_id,branch_name,city,source_note
0,1,Banque Atlas,Derived from source bank_name,Derived; source did not provide branch records
1,2,Banque Hexagone,Derived from source bank_name,Derived; source did not provide branch records
2,3,Britannia Bank,Derived from source bank_name,Derived; source did not provide branch records

--- cards ---

                            dtype  missing  unique
card_id                    object        0     358
account_id                 object        0     270
customer_id                object        0     200
card_number_masked         object        0     358
scheme                     object        0       2
type                       object        0       2
product                    object        0      11
issued_at                  object        0     330
expires_at                 object        0     336
status                     object        0       1
monthly_payment_limit     float64        0       7
monthly_withdrawal_limit  float64        0       7
contactless                  bool        0       2

,card_id,account_id,customer_id,card_number_masked,scheme,type,product,issued_at,expires_at,status,monthly_payment_limit,monthly_withdrawal_limit,contactless
0,K00000001,A00000001,C0000001,5319 **** **** 9889,mastercard,debit,Mastercard Gold,2005-11-06,2008-11-05,active,5000.0,1500.0,True
1,K00000002,A00000004,C0000002,4444 **** **** 0553,visa,debit,Visa Premier,2011-07-16,2014-07-15,active,5000.0,1500.0,True
2,K00000003,A00000007,C0000003,5149 **** **** 6196,mastercard,debit,Mastercard Standard,2021-01-19,2024-01-19,active,2500.0,750.0,True

--- customers ---

                    dtype  missing  unique
customer_id        object        0     200
first_name         object        0     161
last_name          object        0     162
sex                object        0       2
age                 int64        0      60
birth_date         object        0     200
city               object        0      73
postal_code        object        0     192
country            object        0       3
locale_code        object        0       3
family_situation   object        0      12
num_children        int64        0       5
profession         object        0      81
customer_segment   object        0      10
profile            object        0      19
bank_preset        object        0       4
monthly_income    float64        0     200
estimated_wealth  float64        0     200
financial_score     int64        0     130
risk_appetite      object        0       8
customer_since     object        0     199

,customer_id,first_name,last_name,sex,age,birth_date,city,postal_code,country,locale_code,...,num_children,profession,customer_segment,profile,bank_preset,monthly_income,estimated_wealth,financial_score,risk_appetite,customer_since
0,C0000001,Madeleine,Ferreira,F,38,1988-05-28,Paris,75505,France,fr,...,1,manager,PREMIUM,cadre,private,6134.01,75937.92,786,dynamique,2005-11-01
1,C0000002,Wendy,Jackson,F,33,1993-07-19,Bristol,BS8 8WS,United Kingdom,uk,...,1,teacher,STANDARD,family,retail_mass,5345.53,38270.87,721,moderate,2011-07-16
2,C0000003,Gillian,James,F,28,1998-07-20,London,SW9 8RP,United Kingdom,uk,...,2,sales executive,STANDARD,young_professional,young_neobank,2841.03,4130.99,675,moderate,2020-11-29

--- loans ---

                       dtype  missing  unique
loan_id               object        0      95
customer_id           object        0      78
account_id            object        0      78
loan_type             object        0       5
principal            float64        0      93
outstanding_balance  float64        0      86
annual_rate          float64        0      92
term_months            int64        0       9
monthly_payment      float64        0      95
start_date            object        0      94
end_date              object        0      95
payment_day            int64        0      10
status                object        0       2

,loan_id,customer_id,account_id,loan_type,principal,outstanding_balance,annual_rate,term_months,monthly_payment,start_date,end_date,payment_day,status
0,L0000001,C0000001,A00000001,credit_immobilier,157875.41,144404.15,0.0377,180,1149.67,2025-01-17,2040-01-11,4,active
1,L0000002,C0000001,A00000001,credit_auto,13898.47,0.00,0.0448,60,258.98,2016-02-25,2021-02-22,9,closed
2,L0000003,C0000002,A00000004,credit_immobilier,147080.48,113572.10,0.0514,300,871.86,2017-08-30,2042-08-19,4,active

--- merchants ---

                dtype  missing  unique
merchant_id    object        0     254
name           object        0     254
mcc             int64        0      48
category       object        0      12
subcategory    object        0      90
amount_mu     float64        0     110
amount_sigma  float64        0      59
channel        object        0       3
weight        float64        0      10

,merchant_id,name,mcc,category,subcategory,amount_mu,amount_sigma,channel,weight
0,M00001,Carrefour,5411,alimentation,supermarche,58.0,32.0,both,1.0
1,M00002,Leclerc,5411,alimentation,supermarche,62.0,35.0,in_store,1.0
2,M00003,Auchan,5411,alimentation,supermarche,55.0,30.0,both,0.9

--- products ---

                   dtype  missing  unique
product_id         int64        0      24
product_name      object        0      24
product_category  object        0       1
source_note       object        0       1

,product_id,product_name,product_category,source_note
0,1,assurance_vie,Derived from account_type,Derived; source did not provide product records
1,2,brokerage,Derived from account_type,Derived; source did not provide product records
2,3,business_checking,Derived from account_type,Derived; source did not provide product records

--- subscriptions ---

                    dtype  missing  unique
subscription_id    object        0    1333
customer_id        object        0     200
account_id         object        0     214
merchant_name      object        0      65
category           object        0       8
subcategory        object        0      27
amount            float64        0     939
frequency_months    int64        0       2
billing_day         int64        0      28
start_date         object        0     876
end_date           object     1134     172
status             object        0       2

,subscription_id,customer_id,account_id,merchant_name,category,subcategory,amount,frequency_months,billing_day,start_date,end_date,status
0,S00000001,C0000001,A00000001,Amazon Prime,abonnements,streaming_video,6.99,1,8,2024-05-31,NaN,active
1,S00000002,C0000001,A00000001,Engie,energie,gaz,30.00,1,7,2024-07-19,2026-03-04,churned
2,S00000003,C0000001,A00000001,Orange,telecom,mobile,22.91,1,2,2023-09-13,NaN,active

--- transactions ---

                             dtype  missing  unique
transaction_id              object        0  476202
account_id                  object        0     352
customer_id                 object        0     200
transaction_date            object        0  469921
amount                     float64        0   40684
currency                    object        0       3
merchant_name               object        0     473
merchant_category           object        0      24
merchant_mcc                 int64        0      44
transaction_type            object        0       3
payment_channel             object        0       6
city                        object   219459      73
country                     object        0       3
counterparty_iban           object   467586     277
label                       object        0     714
category                    object        0      24
subcategory                 object        0     109
is_subscription               bool        0       2
is_salary                     bool        0       2
is_transfer                   bool        0       2
is_cash_withdrawal            bool        0       2
balance_after_transaction  float64        0  382446
is_foreign                    bool        0       1
original_amount            float64        0   44948
original_currency           object        0       3
fx_rate                    float64        0       1
foreign_fee                float64        0       1
signed_amount              float64        0   44948
source_transaction_type     object        0      12
transaction_status          object        0       1

,transaction_id,account_id,customer_id,transaction_date,amount,currency,merchant_name,merchant_category,merchant_mcc,transaction_type,...,is_cash_withdrawal,balance_after_transaction,is_foreign,original_amount,original_currency,fx_rate,foreign_fee,signed_amount,source_transaction_type,transaction_status
0,70cb19af0c5347bb9d69a2cd6f1918a7,A00000001,C0000001,2023-10-07T12:36:07,4.19,EUR,Brioche Dorée,restauration,5814,Withdrawal,...,False,7491.50,False,-4.19,EUR,1.0,0.0,-4.19,card_payment_contactless,Completed
1,839148d0a1624fb88a88ef9ea5569175,A00000001,C0000001,2023-10-07T09:06:50,34.24,EUR,Lidl,alimentation,5411,Withdrawal,...,False,7457.26,False,-34.24,EUR,1.0,0.0,-34.24,card_payment_contactless,Completed
2,a2d4a6fbc01f418e8a87a8fed7d3b1e4,A00000001,C0000001,2023-10-07T16:17:36,69.67,EUR,Intermarché,alimentation,5411,Withdrawal,...,False,7387.59,False,-69.67,EUR,1.0,0.0,-69.67,card_payment_contactless,Completed

## Review checklist
- Confirm primary keys are unique and non-null.
- Confirm foreign keys match parent tables.
- Identify date, amount, status, and category columns from the actual schema.
- Record any schema differences before editing notebook 02.